[package]
name = "eth-bridge"
version = "0.1.0"
edition = "2018"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
frame-support = { version = "3", default-features = false }
frame-system = { version = "3", default-features = false }
frame-benchmarking = { version = "3", default-features = false, optional = true }
hex-literal = "0.3.1"
libsecp256k1 = { version = "0.3.5", features = ['hmac'], default-features = false }
once_cell = { version = "1.5.2", default-features = false, features = ['alloc', 'unstable'] }
rlp = { version = "0.4.6", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0", features = ["alloc", "derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sp-core = { version = "3", default-features = false }
sp-std = { version = "3", default-features = false }
tiny-keccak = { version = "2", default-features = false }

bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "v3.0.0", package = "pallet-multisig", default-features = false }
ethabi = { git = "https://github.com/vmarkushin/ethabi.git", branch = "no-std", package = "ethabi", default-features = false, features = ["alloc"] }
ethabi-contract = { git = "https://github.com/vmarkushin/ethabi.git", branch = "no-std", package = "ethabi-contract", default-features = false }
ethabi-derive = { git = "https://github.com/vmarkushin/ethabi.git", branch = "no-std", package = "ethabi-derive", default-features = false }
ethereum-types = { git = "https://github.com/vmarkushin/parity-common.git", branch = "no-std", package = "ethereum-types", default-features = false, features = ['serialize', 'codec'] }
jsonrpc-core = { git = "https://github.com/vmarkushin/jsonrpc.git", branch = "no-std", package = "jsonrpc-core", default-features = false }

assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
permissions = { path = "../permissions", default-features = false }

[dev-dependencies]
async-std = { version = "1.5", features = ["attributes", "unstable"] }
currencies = { version = "0.4", package = "orml-currencies", default-features = false }
env_logger = "0.8.1"
frame-executive = { version = "3", default-features = false }
orml-traits = { version = "0.4", package = "orml-traits", default-features = false }
pallet-balances = "3"
pallet-sudo = "3"
parity-util-mem = { version = "0.9", default-features = false }
parking_lot = "0.11.0"
sp-core = { version = "3", default-features = false, features = ["full_crypto"] }
sp-keystore = { version = "0.9", default-features = false }
tokens = { version = "0.4", package = "orml-tokens" }
tokio = { version = "0.2.13", default-features = false, features = ["macros"] }

assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
permissions = { path = "../permissions" }

[features]
default = ['std']
std = [
    'bridge-multisig/std',
    'codec/std',
    'ethereum-types/std',
    'frame-support/std',
    'frame-system/std',
    'jsonrpc-core/std',
    'libsecp256k1/std',
    'rlp/std',
    'rustc-hex/std',
    'serde_json/std',
    'serde/std',
    'sp-core/std',
    'sp-std/std',
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]