[package]
edition = "2018"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
name = "iroha-migration"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "3", default-features = false, optional = true }
frame-support = { version = "3", default-features = false }
frame-system = { version = "3", default-features = false }
hex = { version = "0.4.2", default-features = false }
hex-literal = { version = "0.3.1", optional = true }
pallet-multisig = { version = "3", default-features = false }
serde = { version = "1.0.101", default-features = false, optional = true, features = ["derive"] }
sha3 = { version = "0.9.1", default-features = false }
sp-std = { version = "3", default-features = false }

ed25519-dalek-iroha = { git = "https://github.com/soramitsu/sora2-ed25519-dalek-iroha.git", branch = "develop", default-features = false, features = ["u64_backend"] }

assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
referral-system = { path = "../referral-system", default-features = false }
technical = { path = "../technical", default-features = false }

[dev-dependencies]
currencies = { version = "0.4", package = "orml-currencies" }
pallet-balances = "3"
parity-util-mem = { version = "0.9", default-features = false }
sp-core = { version = "3", default-features = false }
sp-io = { version = "3", default-features = false }
sp-runtime = { version = "3", default-features = false }
tokens = { version = "0.4", package = "orml-tokens" }

assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
permissions = { path = "../permissions" }
referral-system = { path = "../referral-system" }
technical = { path = "../technical" }

[features]
default = ["std"]

std = [
    "codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-multisig/std",
    "serde",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "hex-literal"
]
