[package]
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2018'
name = 'xor-fee'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
frame-support = { version = "3", default-features = false }
frame-system = { version = "3", default-features = false }
pallet-transaction-payment = { version = "3", default-features = false }
serde = { version = "1.0.101", features = ["derive"], optional = true }
sp-arithmetic = { version = "3", default-features = false }
sp-runtime = { version = "3", default-features = false }
sp-std = { version = "3", default-features = false }
traits = { version = "0.4", package = "orml-traits", default-features = false }

pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "v3.0.0"}

assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
liquidity-proxy = { path = "../liquidity-proxy", default-features = false }
referral-system = { path = "../referral-system", default-features = false }

[dev-dependencies]
currencies = { version = "0.4", package = "orml-currencies" }
pallet-balances = { version = "3", default-features = false }
pallet-session = { version = "3", default-features = false }
pallet-timestamp = { version = "3", default-features = false }
sp-core = { version = "3", default-features = false }
sp-io = { version = "3", default-features = false }
sp-runtime = { version = "3", default-features = false }
tokens = { version = "0.4", package = "orml-tokens" }

common = { path = "../../common", features = ["test"] }
dex-manager = { path = "../dex-manager" }
mock-liquidity-source = { path = "../mock-liquidity-source" }
permissions = { path = "../permissions" }
referral-system = { path = "../referral-system" }
technical = { path = "../technical" }
trading-pair = { path = "../trading-pair" }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'traits/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-staking/std',
    'pallet-transaction-payment/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
]
