[package]
edition = '2018'
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
name = 'framenode-runtime'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
hex-literal = "0.3.1"
serde = { features = ['derive'], optional = true, version = '1.0.101' }
common = { path = "../common", default-features = false }
faucet = { path = "../pallets/faucet", default-features = false, optional = true }
assets = { path = "../pallets/assets", default-features = false }
bonding-curve-pool = { path = "../pallets/bonding-curve-pool", default-features = false }
multicollateral-bonding-curve-pool = { path = "../pallets/multicollateral-bonding-curve-pool", default-features = false }
dex-api = { path = "../pallets/dex-api", default-features = false }
dex-manager = { path = "../pallets/dex-manager", default-features = false }
farming = { path = "../pallets/farming", default-features = false}
iroha-migration = { path = "../pallets/iroha-migration", default-features = false }
liquidity-proxy = { path = "../pallets/liquidity-proxy", default-features = false}
mock-liquidity-source = { path = "../pallets/mock-liquidity-source", default-features = false}
permissions = { path = "../pallets/permissions", default-features = false}
pool-xyk = { path = "../pallets/pool-xyk", default-features = false}
referral-system = { path = "../pallets/referral-system", default-features = false}
rewards = { path = "../pallets/rewards", default-features = false }
rewards-runtime-api = { path = "../pallets/rewards/runtime-api", default-features = false }
technical = { path = "../pallets/technical", default-features = false}
trading-pair = { path = "../pallets/trading-pair", default-features = false}
xor-fee = { path = "../pallets/xor-fee", default-features = false}
dex-runtime-api = { path = "../pallets/dex-api/runtime-api", default-features = false}
dex-manager-runtime-api = { path = "../pallets/dex-manager/runtime-api", default-features = false}
trading-pair-runtime-api = { path = "../pallets/trading-pair/runtime-api", default-features = false}
assets-runtime-api = { path = "../pallets/assets/runtime-api", default-features = false}
liquidity-proxy-runtime-api = { path = "../pallets/liquidity-proxy/runtime-api", default-features = false}
eth-bridge = { path = "../pallets/eth-bridge", default-features = false }
eth-bridge-runtime-api = { path = "../pallets/eth-bridge/runtime-api", default-features = false }
bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "v3.0.0", package = "pallet-multisig", default-features = false }
farming-runtime-api = { path = "../pallets/farming/runtime-api", default-features = false}
iroha-migration-runtime-api = { path = "../pallets/iroha-migration/runtime-api", default-features = false }
pswap-distribution = { path = "../pallets/pswap-distribution", default-features = false }
pswap-distribution-runtime-api = { path = "../pallets/pswap-distribution/runtime-api", default-features = false }
liquidity-proxy-benchmarking = { path = "../pallets/liquidity-proxy/benchmarking", default-features = false, optional = true }
pool-xyk-benchmarking = { path = "../pallets/pool-xyk/benchmarking", default-features = false, optional = true }
dex-api-benchmarking = { path = "../pallets/dex-api/benchmarking", default-features = false, optional = true }

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = '3' }
pallet-collective = { default-features = false, version = '3' }
pallet-democracy = { default-features = false, version = '3' }
frame-executive = { default-features = false, version = '3' }
frame-support = { default-features = false, version = '3' }
frame-system = { default-features = false, version = '3' }
frame-system-benchmarking = { default-features = false, optional = true, version = '3' }
frame-system-rpc-runtime-api = { default-features = false, version = '3' }
pallet-aura = { default-features = false, version = '3' }
pallet-balances = { default-features = false, version = '3' }
pallet-grandpa = { default-features = false, version = '3' }
pallet-babe = { default-features = false, version = '3' }
pallet-im-online = { default-features = false, version = '3' }
pallet-multisig = { version = "3", default-features = false }
pallet-offences = { default-features = false, version = '3' }
pallet-randomness-collective-flip = { default-features = false, version = '3' }
pallet-sudo = { default-features = false, version = '3' }
pallet-timestamp = { default-features = false, version = '3' }
pallet-scheduler = { default-features = false, version = '3' }
#pallet-session = { default-features = false, version = '3' }
pallet-session = { default-features = false, features = ["historical"], version = '3' }
pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "v3.0.0"}
pallet-transaction-payment = { version = '3', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = '3', default-features = false }
pallet-utility = { default-features = false, version = '3' }

sp-api = { default-features = false, version = '3' }
sp-block-builder = { default-features = false, version = '3' }
sp-consensus-aura = { default-features = false, version = '0.9' }
sp-consensus-babe = { default-features = false, version = '0.9' }
sp-core = { default-features = false, version = '3' }
sp-inherents = { default-features = false, version = '3' }
sp-offchain = { default-features = false, version = '3' }
sp-runtime = { default-features = false, version = '3' }
sp-session = { default-features = false, version = '3' }
sp-std = { default-features = false, version = '3' }
sp-transaction-pool = { default-features = false, version = '3' }
sp-version = { default-features = false, version = '3' }
sp-staking = { default-features = false, version = '3' }
pallet-authorship = { default-features = false, version = '3' }

# Other
currencies = { version = "0.4", package = "orml-currencies", default-features = false }
static_assertions = "1.1.0"
tokens = { version = "0.4", package = "orml-tokens", default-features = false }
traits = { version = "0.4", package = "orml-traits", default-features = false }

[features]
default = ['std']

std = [
    'codec/std',
    'serde',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-aura/std',
    'pallet-babe/std',
    'pallet-balances/std',
    'pallet-collective/std',
    'pallet-democracy/std',
    'pallet-grandpa/std',
    'pallet-im-online/std',
    'pallet-offences/std',
    'pallet-randomness-collective-flip/std',
    'pallet-scheduler/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-session/std',
    'pallet-staking/std',
    'pallet-utility/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'sp-staking/std',
    'pallet-authorship/std',
    'common/std',
    'assets/std',
    'bonding-curve-pool/std',
    'multicollateral-bonding-curve-pool/std',
    'dex-api/std',
    'dex-manager/std',
    'eth-bridge/std',
    'eth-bridge-runtime-api/std',
    'farming/std',
    'farming-runtime-api/std',
    'faucet?/std',
    'iroha-migration/std',
    'iroha-migration-runtime-api/std',
    'liquidity-proxy/std',
    'mock-liquidity-source/std',
    'bridge-multisig/std',
    'permissions/std',
    'pool-xyk/std',
    'referral-system/std',
    'rewards/std',
    'rewards-runtime-api/std',
    'technical/std',
    'trading-pair/std',
    'xor-fee/std',
    'dex-runtime-api/std',
    'dex-manager-runtime-api/std',
    'trading-pair-runtime-api/std',
    'assets-runtime-api/std',
    'liquidity-proxy-runtime-api/std',
    'pswap-distribution/std',
    'pswap-distribution-runtime-api/std',
]

private-net = ["faucet"]

runtime-benchmarks = [
    "assets/runtime-benchmarks",
    "eth-bridge/runtime-benchmarks",
    "dex-api-benchmarking",
    "faucet?/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking",
    "frame-system/runtime-benchmarks",
    "iroha-migration/runtime-benchmarks",
    "liquidity-proxy-benchmarking",
    "pallet-collective/runtime-benchmarks",
    "pool-xyk-benchmarking",
    "rewards/runtime-benchmarks",
    "technical/runtime-benchmarks",
    "trading-pair/runtime-benchmarks",
    "multicollateral-bonding-curve-pool/runtime-benchmarks",
    "pswap-distribution/runtime-benchmarks",
]

reduced-pswap-reward-periods = []
